import Head from 'next/head'
import 'bootstrap/dist/css/bootstrap.min.css';
import { NavBar } from '../components/Navbar';
import { Index } from './home';

export default function Home() {
  return (
    <div>
      <Head>
        <title>MCjade | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar />
      <Index />
    </div>
  )
}
